{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- $external_socket := .Values.service.external.enabled }}
  {{- range $objectKey, $objectValue := .Values.config.inputs }}
  {{- range $key, $value := . -}}
    {{- $tp := typeOf $value -}}
    {{- if eq $key "influxdb_listener" }}
  - port: {{ trimPrefix ":" $value.service_address | int64 }}
    targetPort: {{ trimPrefix ":" $value.service_address | int64 }}
    name: "http-listener"
    {{- end }}
    {{- if and (eq $key "socket_listener") (not $external_socket) }}
  - port: {{ trimPrefix "tcp://:" $value.service_address | int64 }}
    targetPort: {{ trimPrefix "tcp://:" $value.service_address | int64 }}
    protocol: TCP
    name: "socket-listener"
    {{- end }}
  {{- end -}}
  {{- end }}
  selector:
    app: {{ template "fullname" . }}
{{- end -}}
{{- if and .Values.service.enabled .Values.service.external.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-tcp
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
spec:
{{- with .Values.service.external.socket_listener }}
  type: {{ .type }}
  ports:
  - port: {{ .servicePort | int64 }}
    targetPort: {{ .servicePort | int64 }}
    nodePort: {{ .nodePort | int64 }}
    name: "socket-listener"
{{- end}}
  selector:
    app: {{ template "fullname" . }}
{{- end -}}
