{{- if .Values.createUsers.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "fullname" . }}-auth
data:
  {{- if .Values.createUsers.adminUser.password }}
  influxdb-password:  {{ .Values.createUsers.adminUser.password | b64enc | quote }}
  {{- else }}
  influxdb-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  influxdb-user: {{ .Values.createUsers.adminUser.username | b64enc | quote }}
{{- end -}}
