{{- if .Values.createUsers.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  name: {{ template "fullname" . }}-create-users
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  activeDeadlineSeconds: {{ .Values.createUsers.activeDeadlineSeconds }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        release: "{{ .Release.Name }}"
    spec:
      containers:
      - name: {{ template "fullname" . }}-set-auth
        image: {{ .Values.createUsers.image | quote }}
        env:
          - name: INFLUXDB_USER
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}-auth
                key: influxdb-user
          - name: INFLUXDB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}-auth
                key: influxdb-password
        args:
          - "/bin/sh"
          - "-c"
          - |
             curl -XPOST 'http://{{ template "fullname" . }}:{{ .Values.config.http.bind_address }}/query' \
             --data-urlencode \
             "q=CREATE USER \"${INFLUXDB_USER}\" WITH PASSWORD '${INFLUXDB_PASSWORD}' {{ .Values.createUsers.adminUser.privileges }}"
             {{- if gt (len .Values.createUsers.users) 0 }}
             curl -XPOST "http://{{ template "fullname" . }}:{{ .Values.config.http.bind_address }}/query?u=${INFLUXDB_USER}&p=${INFLUXDB_PASSWORD}" \
             --data-urlencode \
             "q={{ template "users" .Values.createUsers.users }}"
             {{- end }}
      restartPolicy: {{ .Values.createUsers.restartPolicy }}
{{- end -}}
