{{- if .Values.persistence }}
# PersistentVolume for InfluxDB
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "fullname" .}}-pv
spec:
  capacity:
    storage: {{.Values.persistence.size | quote}}
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ template "fullname" . }}
  local:
    path: {{.Values.persistence.storagePath}}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
            - {{.Values.persistence.nodeAffinity.host}}
{{- end }}