#######################################################
# Kapacitor values.yaml (modified by Digital Inspire) #
#######################################################

# this value is used in _helpers.tpl for the fullname
# fullname is used for all naming conventions of the influxdb config files
namePrefix: influxdata

## kapacitor image version
## ref: https://hub.docker.com/r/library/kapacitor/tags/
image:
  repository: "kapacitor"
  tag: "1.5.2"
  pullPolicy: "IfNotPresent"

## Specify a service type, defaults to NodePort
## ref: http://kubernetes.io/docs/user-guide/services/
service:
  type: ClusterIP

## Persist data to a persistent volume
## This does not delete data after a shutdown or restart of the Pod
persistence:
  accessMode: ReadWriteOnce
  size: 4Gi #define size of volume for influxdb (Gi=Gigabyte)
  # Storage path where persistent volume (pv) is mounted on machine
  # NOTE: This folder needs to be created on the actual or storage!
  storagePath: /opt/kapacitor/
  # set a node affinity for the pv and stateful set of the influxdb
  # host = hostname of machine where pv should be mounted
  # NOTE: select a node where storage capacity is available
  nodeAffinity:
    host: worker1.k8scluster.local

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
resources:
  requests:
    memory: 256Mi
    cpu: 0.1
  limits:
    memory: 2Gi
    cpu: 2

## Set the URL of InfluxDB instance to create subscription on
## ref: https://docs.influxdata.com/kapacitor/v1.5/introduction/getting_started/
influxURL: http://influxdata-inflxudb:8086
