#######################################################
# Kapacitor values.yaml (modified by Digital Inspire) #
#######################################################

# this value is used in _helpers.tpl for the fullname
# fullname is used for all naming conventions of the influxdb config files
namePrefix: influxdata

## kapacitor image version
## ref: https://hub.docker.com/r/library/kapacitor/tags/
image:
  repository: "kapacitor"
  tag: "1.5.2"
  pullPolicy: "IfNotPresent"

## Specify a service type, defaults to NodePort
## ref: http://kubernetes.io/docs/user-guide/services/
service:
  type: ClusterIP

## Persist data to a persistent volume
## This does not delete data after a shutdown or restart of the Pod
persistence:
  accessMode: ReadWriteOnce
  size: 4Gi #define size of volume for influxdb (Gi=Gigabyte)
  # Storage path where persistent volume (pv) is mounted on machine
  # NOTE: This folder needs to be created on the actual storage system!
  storagePath: /opt/kapacitor/
  # set a node affinity for the pv and stateful set of the influxdb
  # host = hostname of machine where pv should be mounted
  # NOTE: select a node where storage capacity and folder is available
  nodeAffinity:
    host: worker1.k8scluster.local

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
resources:
  requests:
    memory: 256Mi
    cpu: 0.1
  limits:
    memory: 2Gi
    cpu: 2


## Set the URL of InfluxDB instance to create subscription on
## NOTE: If this value is not set, the stateful set will not be deployed!!
## ref: https://docs.influxdata.com/kapacitor/v1.5/introduction/getting_started/
influxdb:
  url: http://influxdata-influxdb:8086
  # Set user credentials in order for the Kapacitor to successfully connect to 
  # influxdb
  username: "admin"
  password: "admin"


config:
  data_dir: /var/lib/kapacitor
  skip_config_overrides: false
  default_retention_policy: ""
  http:
    bind_address: ":9092"
    auth_enabled: false
    log_enabled: false
    write_tracing: false
    pprof_enabled: false
    https_enabled: false
    shutdown_timeout: "10s"
  replay:
    dir: /var/lib/kapacitor/replay
  storage:
    boltdb: /var/lib/kapacitor/kapacitor.db
  task:
    dir: /var/lib/kapacitor/tasks
    snapshot_interval: "1m0s"
  influxdb:
    enabled: true
    name: "default"
    default: false
    timeout: "0s"
    disable_subscriptions: false
    subscription_protocol: "http"
    http_port: 0
    udp_bind: ""
    udp_buffer: 1000
    udp_read_buffer: 0
    startup_timeout: "5m0s"
    subscriptions_sync_interval: "1m0s"
    excluded_subscriptions:
      - db: "_kapacitor"
        retention: "autogen"
  config_override:
    enabled: true
  logging:
    file: "STDERR"
    level: "ERROR" # INFO, ERROR, ...
  deadman:
    interval: "10s"
    threshold: 0.1
    id: ""
    message: ""
    global: false
  slack:
    enabled: false
    url: ""
    channel: ""
    username: "kapacitor"
    icon_emoji: ""
    global: false
    state_changes_only: false
    ssl_ca: ""
    ssl_cert: ""
    ssl_key: ""
    insecure_skip_verify: false
