########################################################
# Chronograf values.yaml (modified by Digital Inspire) #
########################################################

# this value is used in _helpers.tpl for the fullname
# fullname is used for all naming conventions of the influxdb config files
# Example: influxdata-chronograf-<...>
namePrefix: influxdata

## influxdb image repository and tag that is used for the Pod (i.e. docker container)
## ref: https://hub.docker.com/r/library/chronograf/tags/
image:
  repository: "chronograf"
  tag: "1.7.11"
  pullPolicy: IfNotPresent

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
resources:
  requests:
    memory: 256Mi
    cpu: 0.1
  limits:
    memory: 2Gi
    cpu: 2

## Specify a service type
## ClusterIP is default as Ingress is used to allow for external access
## ref: http://kubernetes.io/docs/user-guide/services/
service:
  type: ClusterIP

# Ingress Object for InfluxDB
# In short, this allows the InfluxDB being accessed from the outside world
# Also allows for SSL termination and usage of hostnames and tls/ssl certs
# If disabled, InfluxDB won't be accesible from the outside
# ref: https://kubernetes.io/docs/concepts/services-networking/ingress/ 
ingress:
  enabled: true
  # hostname is an already registered domain name that points to one of your worker nodes!
  # as ingress controller is a Deamon Set, each worker node (except master) can be used to access
  # influxdb via ingress or the specified hostname!
  # NOTE: if hostname is an empty string, the actual ip address of a node can be used to access influxdb
  hostname: ""
  # tls should only be used if a hostname is given!
  # if tls is enabled, ensure that a certificate for the hostname is provided under "secretName"
  tls: false
  # this attribute points to an existing K8s secret tls
  # Consult the README.md in order to see how to create a K8s Secret TLS
  secretName: my-tls-cert
  annotations:
    kubernetes.io/ingress.class: "nginx"

## OAuth Settings for OAuth Providers
## More information -> https://docs.influxdata.com/chronograf/v1.7/administration/managing-security/
oauth:
  # Need to set to true to use any of the oauth options
  enabled: false
  # Used for JWT to support running multiple copies of Chronograf
  token_secret: CHANGE_ME
  github:
    enabled: false
    client_id: CHANGE_ME
    client_secret: CHANGE_ME
    # This is a comma seperated list of GH organizations (OPTIONAL)
    gh_orgs: ""
  google:
    enabled: false
    client_id: CHANGE_ME
    client_secret: CHANGE_ME
    public_url: "" # eg. http://chronograf.foobar.com
    # This is a comma seperated list of Google Apps domains (OPTIONAL)
    google_domains: ""
  heroku:
    enabled: false
    client_id: CHANGE_ME
    client_secret: CHANGE_ME
    # This is a comma seperated list of Heroku organizations (OPTIONAL)
    he_orgs: ""

## Extra environment variables that will be passed onto deployment pods
env: {}

## The name of a secret in the same kubernetes namespace which contain values to be added to the environment
## This can be useful for auth tokens, etc
envFromSecret: ""
