apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  kapacitor.conf: |+  
    hostname = "{{ template "fullname" . }}.{{.Release.Namespace}}"
    data_dir = {{ .Values.config.data_dir | quote }}
    skip-config-overrides = {{ .Values.config.skip_config_overrides }}
    default-retention-policy = {{ .Values.config.default_retention_policy | quote }}
    [http]
      bind-address = {{ .Values.config.http.bind_address | quote }}
      auth-enabled = {{ .Values.config.http.auth_enabled }}
      log-enabled = {{ .Values.config.http.log_enabled }}
      write-tracing = {{ .Values.config.http.write_tracing }}
      pprof-enabled = {{ .Values.config.http.pprof_enabled }}
      https-enabled = {{ .Values.config.http.https_enabled }}
      shutdown-timeout = {{ .Values.config.http.shutdown_timeout | quote }}
    [replay]
      dir = {{ .Values.config.replay.dir | quote }}
    [storage]
      boltdb = {{ .Values.config.storage.boltdb | quote }}
    [task]
      dir = {{ .Values.config.task.dir | quote }}
      snapshot-interval = {{ .Values.config.task.snapshot_interval | quote }}
    [[influxdb]]
      enabled = {{ .Values.config.influxdb.enabled }}
      name = "{{ .Values.config.influxdb.name }}"
      default = {{ .Values.config.influxdb.default }}
      urls = [{{ .Values.influxdb.url | quote }}]
      username = {{ .Values.influxdb.username | quote }}
      password = {{ .Values.influxdb.password | quote }}
      timeout = "{{ .Values.config.influxdb.timeout }}"
      disable-subscriptions = {{ .Values.config.influxdb.disable_subscriptions }}
      subscription-protocol = "{{ .Values.config.influxdb.subscription_protocol }}"
      kapacitor-hostname = "{{ template "fullname" . }}.{{.Release.Namespace}}"
      http-port = {{ .Values.config.influxdb.http_port }}
      udp-bind = {{ .Values.config.influxdb.udp_bind | quote }}
      udp-buffer = {{ .Values.config.influxdb.udp_buffer }}
      udp-read-buffer = {{ .Values.config.influxdb.udp_read_buffer }}
      startup-timeout = "{{ .Values.config.influxdb.startup_timeout }}"
      subscriptions-sync-interval = "{{ .Values.config.influxdb.subscriptions_sync_interval }}"
      {{ template "influxdb-excl-subs" .Values.config.influxdb.excluded_subscriptions }}
    [logging]
      file = "{{ .Values.config.logging.file }}"
      level = "{{ .Values.config.logging.level }}"
    [config-override]
      enabled = {{ .Values.config.config_override.enabled }}
    [deadman]
      interval = "{{ .Values.config.deadman.interval }}"
      threshold = {{ .Values.config.deadman.threshold | float64 }}
      id = {{ .Values.config.deadman.id | quote }}
      message = {{ .Values.config.deadman.message | quote }}
      global = {{ .Values.config.deadman.global }}
    [slack]
      enabled = {{ .Values.config.slack.enabled }}
      url = {{ .Values.config.slack.url | quote }}
      channel = {{ .Values.config.slack.channel | quote }}
      username = "{{ .Values.config.slack.username }}"
      icon-emoji = "{{ .Values.config.slack.icon_emoji }}"
      global = {{ .Values.config.slack.global }}
      state-changes-only = {{ .Values.config.slack.state_changes_only }}
      ssl-ca = "{{ .Values.config.slack.ssl_ca }}"
      ssl-cert = "{{ .Values.config.slack.ssl_cert }}"
      ssl-key = "{{ .Values.config.slack.ssl_key }}"
      insecure-skip-verify = {{ .Values.config.slack.insecure_skip_verify }}
##    [alerta]
##      enabled = false
##      url = ""
##      insecure-skip-verify = false
##      token = ""
##      token-prefix = ""
##      environment = ""
##      origin = ""
##    [collectd]
##      enabled = false
##      bind-address = ":25826"
##      database = "collectd"
##      retention-policy = ""
##      batch-size = 5000
##      batch-pending = 10
##      batch-timeout = "10s"
##      read-buffer = 0
##      typesdb = "/usr/share/collectd/types.db"
##    [opentsdb]
##      enabled = false
##      bind-address = ":4242"
##      database = "opentsdb"
##      retention-policy = ""
##      consistency-level = "one"
##      tls-enabled = false
##      certificate = "/etc/ssl/influxdb.pem"
##      batch-size = 1000
##      batch-pending = 5
##      batch-timeout = "1s"
##      log-point-errors = true
##    [talk]
##      enabled = false
##      url = ""
##      author_name = ""
##    [telegram]
##      enabled = false
##      url = "https://api.telegram.org/bot"
##      token = ""
##      chat-id = ""
##      parse-mode = ""
##      disable-web-page-preview = false
##      disable-notification = false
##      global = false
##      state-changes-only = false
##    [hipchat]
##      enabled = false
##      url = ""
##      token = ""
##      room = ""
##      global = false
##      state-changes-only = false
##    [opsgenie]
##      enabled = false
##      api-key = ""
##      url = "https://api.opsgenie.com/v1/json/alert"
##      recovery_url = "https://api.opsgenie.com/v1/json/alert/note"
##      global = false
##    [pagerduty]
##      enabled = false
##      url = "https://events.pagerduty.com/generic/2010-04-15/create_event.json"
##      service-key = ""
##      global = false
##    [pushover]
##      enabled = false
##      token = ""
##      user-key = ""
##      url = "https://api.pushover.net/1/messages.json"
##    [smtp]
##      enabled = false
##      host = "localhost"
##      port = 25
##      username = ""
##      password = ""
##      no-verify = false
##      global = false
##      state-changes-only = false
##      from = ""
##      idle-timeout = "30s"
##    [snmptrap]
##      enabled = false
##      addr = "localhost:162"
##      community = "kapacitor"
##      retries = 1
##    [sensu]
##      enabled = false
##      addr = ""
##      source = "Kapacitor"
##    [victorops]
##      enabled = false
##      api-key = ""
##      routing-key = ""
##      url = "https://alert.victorops.com/integrations/generic/20131114/alert"
##      global = false
##    [reporting]
##      enabled = true
##      url = "https://usage.influxdata.com"
##    [stats]
##      enabled = true
##      stats-interval = "10s"
##      database = "_kapacitor"
##      retention-policy = "autogen"
##      timing-sample-rate = 0.1
##      timing-movavg-size = 1000
##    [[kubernetes]]
##      id = "kubernetes-pod"
##      enabled = true
##      in-cluster = true
##      resource = "pod"
##    [[scraper]]
##      enabled = true
##      name = "prometheus-node"
##      discoverer-id = "kubernetes-node"
##      discoverer-service = "kubernetes"
##      db = "prometheus_raw"
##      rp = "autogen"  
##      type = "prometheus"
##      scheme = "http"
##      metrics-path = "/metrics"
##      scrape-interval = "10s"
##      scrape-timeout = "10s"
